package day05;

import java.util.Scanner;

public class ExceptionDemo {
    public static void main(String[] args){
        Scanner scanner = new Scanner(System.in);
        System.out.println("请输入第一个数字");
        int num1 = scanner.nextInt();
        System.out.println("请输入第二个数字");
        int num2 = scanner.nextInt();
    try {
        int result = divide(num1, num2);
        System.out.println("输出结果为" + result);
    }catch(ArithmeticException e) {
        System.out.println("发生错误" + e.getMessage());
    }catch(Exception e){
        System.out.println("发生位置错误" + e.getMessage());
    }
    }
    public static  int divide( int a, int b ){
        if (b == 0){
            System.out.println("除数不可以为0");
        }
        return a/b;
        }
    }

import java.util.logging.Level;
import java.util.logging.Logger;

public class LogDemo {
   private static final Logger logger = Logger.getLogger(LogDemo.class.getName());
   public static void main(String[] args){
      try {
         int result = dirvid( 10 , 0);
         System.out.println("结果是：" + result);
      }catch (ArithmeticException e){
         logger.log(Level.SEVERE,"发生错误");
      }catch(Exception e){
         logger.log(Level.WARNING,"发生未知错误" , e);

      }finally {
         logger.log(Level.INFO,"程序结束。");
      }
   }
   public static int dirvid(int a,int b){
      if (b==0){
         throw new ArithmeticException("除数不能为0");
      }
      return a/b;
   }
}
